version: "3.0"
services:
  postgres:
    image: postgres
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/postgres

  redis:
    image: bitnami/redis:latest
    ports:
      - '6379:6379'
    environment:
      ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - redis_data:/bitnami

  oauth:
    image: oauth-muhammad-alif-saddid
    depends_on:
      postgres:
        condition: service_started
      redis:
        condition: service_started
    ports:
      - '28250:8080'
    

volumes:
  redis_data:
    driver: local
  postgres_data:
    driver: local